namespace Cadastro.API.Model
{
    public class Usuario
    {
        public long Id { get; set; }
        public string razSocCad { get; set; }
        public string cnpjCad { get; set; }
        public string endCad { get; set; }
        public string cepCad { get; set; }
        public string cidadeCad { get; set; }
        public string estadoCad { get; set; }
        public string socioCad { get; set; }
        public string cargoCad { get; set; }
        public string cpf1Cad { get; set; }
        public string rg1Cad { get; set; }
        public string cpf2Cad { get; set; }
        public string rg2Cad { get; set; }
        public string end2Cad { get; set; }
        public string cep2Cad { get; set; }
        public string data { get; set; }
        public string razSoc { get; set; }
        public string cnpj { get; set; }
        public string inscEst { get; set; }
        public string inscMun { get; set; }
        public string fone { get; set; }
        public string fone2 { get; set; }
        public string email { get; set; }
        public string nomeFin { get; set; }
        public string fone3 { get; set; }
        public string emailFin { get; set; }
        public string cargo { get; set; }
        public string contMv { get; set; }
        public string cep { get; set; }
        public int numero { get; set; }
        public string complemento { get; set; }
        public string rua { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
        public string conta { get; set; }
        public string agencia { get; set; }
        public int op { get; set; }
        public string banco { get; set; }
        public string favorecido { get; set; }
        public string razSoc3 { get; set; }
        public bool radio1 { get; set; }
        public bool radio2 { get; set; }
        public bool radio3 { get; set; }
        public bool radio4 { get; set; }
        public string textarea5 { get; set; }
        public string textarea6 { get; set; }
        public bool radio7 { get; set; }
        public string textarea7 { get; set; }
        public bool radio8 { get; set; }
        public string textarea8 { get; set; }
        public bool radio9 { get; set; }
        public string textarea9 { get; set; }
        public bool radio10 { get; set; }
        public string textarea10 { get; set; }
        public bool radio11 { get; set; }
        public string textarea11 { get; set; }
        public bool radio12 { get; set; }
        public string textarea12 { get; set; }
        public bool radio13 { get; set; }
        public string textarea13 { get; set; }
        public bool radio14 { get; set; }
        public bool radio15 { get; set; }
        public string textarea15 { get; set; }
        public bool radio16 { get; set; }
        public string textarea16 { get; set; }
        public bool radio17 { get; set; }
        public bool radio18 { get; set; }
        public bool radio19 { get; set; }
        public string textarea19 { get; set; }
        public bool radio20 { get; set; }
        public string data2 { get; set; }
        public string nomeLeg { get; set; }
        public string rgRep { get; set; }
        public string cargoRep { get; set; }
    }

}